service: jsonp

provider:
  name: aws
  runtime: nodejs6.10
  # only deploy production, because of https://github.com/amplify-education/serverless-domain-manager/issues/60
  stage: prod
  # required for custom domains
  # https://serverless.com/blog/serverless-api-gateway-domain/#getting-a-certificate-for-your-domain
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: jsonp.afeld.me
    createRoute53Record: false
